// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_4PwYMdXdWICtL8ulWzchQwCeNHCzlg',
    appId: '1:655702546630:web:2f49633dfede5910795fc7',
    messagingSenderId: '655702546630',
    projectId: 'recyclego-64b10',
    authDomain: 'recyclego-64b10.firebaseapp.com',
    storageBucket: 'recyclego-64b10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXoXYby344tfSeRkXiNvDFNeLFsxT_aew',
    appId: '1:655702546630:android:b56d665fe2a97bd9795fc7',
    messagingSenderId: '655702546630',
    projectId: 'recyclego-64b10',
    storageBucket: 'recyclego-64b10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3h98vQYjMcfe_zCk4DkvYY-JPvQIPGrE',
    appId: '1:655702546630:ios:90b15b3de6a7b576795fc7',
    messagingSenderId: '655702546630',
    projectId: 'recyclego-64b10',
    storageBucket: 'recyclego-64b10.appspot.com',
    iosBundleId: 'com.example.recycleGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3h98vQYjMcfe_zCk4DkvYY-JPvQIPGrE',
    appId: '1:655702546630:ios:6357e7cf5954653b795fc7',
    messagingSenderId: '655702546630',
    projectId: 'recyclego-64b10',
    storageBucket: 'recyclego-64b10.appspot.com',
    iosBundleId: 'com.example.recycleGo.RunnerTests',
  );
}
